export const projects = [
  {
    slug: "routeeye",
    tag: "Fleet operations",
    title: "RouteEye",
    href: "https://routeeye.io/",
    role: "Full-stack developer",
    year: "2025",
    impact: "Made live vehicle movement easier to understand and act on for dispatch teams.",
    summary: "A real-time tracking platform for route intelligence, ETAs, geospatial coordination, and operational control.",
    context: "The product needed to translate changing vehicle data and real route constraints into a dependable operations experience.",
    contribution: [
      "Built route and trip logic for one-way and round-trip operational scenarios.",
      "Connected Google Maps, SSE, Redis, and AWS Lambda for movement and alert updates.",
      "Delivered features across the Node.js backend, React interface, MySQL, and Prisma data layer.",
    ],
    stack: ["Node.js", "React.js", "MySQL", "Redis", "AWS Lambda", "Google Maps"],
  },
  {
    slug: "kalrav-ai",
    tag: "AI agent platform",
    title: "Kalrav AI",
    href: "https://kalrav.ai/",
    role: "Full-stack developer",
    year: "2025",
    impact: "Reduced the effort required to embed, connect, and adopt an AI agent across customer products.",
    summary: "A connected AI product for conversational experiences, business automation, lead workflows, and knowledge sources.",
    context: "Customers needed an agent that could fit their existing websites and business systems instead of becoming another isolated tool.",
    contribution: [
      "Built embeddable widgets, agent setup flows, training sources, and connected automations.",
      "Supported React, Next.js, Vue, Angular, and vanilla integration paths.",
      "Published @irisidea/kalrav-ai to make repeat adoption faster and more consistent.",
    ],
    stack: ["TypeScript", "React.js", "Node.js", "MongoDB", "NPM", "Business integrations"],
  },
  {
    slug: "ecai",
    tag: "Enterprise AI",
    title: "ECAI",
    href: "/about#experience",
    role: "Full-stack developer",
    year: "2024",
    impact: "Brought secure access, connected files, and streaming AI interactions into one coherent workflow.",
    summary: "An enterprise AI experience for model interaction, file connectivity, collaboration, and real-time responses.",
    context: "The challenge was to make identity, document access, collaboration, and AI responses feel like one product rather than separate utilities.",
    contribution: [
      "Owned frontend architecture and connected workflow behavior across the product.",
      "Integrated Microsoft Entra ID, OneDrive, and Microsoft Graph API flows.",
      "Built SSE-based response loops for a more responsive AI experience.",
    ],
    stack: ["React.js", "TypeScript", "Redux", "Entra ID", "Microsoft Graph", "SSE"],
  },
  {
    slug: "yellowowl",
    tag: "Education platform",
    title: "YellowOwl",
    href: "/about#yellowowl",
    role: "Full-stack developer",
    year: "2024",
    impact: "Secured education workflows and made teacher reporting easier to generate and review.",
    summary: "An education product with secure access, teacher dashboards, CMS-backed workflows, automated reports, and mobile support.",
    context: "The platform needed dependable authentication, content workflows, and reporting tools across web and companion mobile experiences.",
    contribution: [
      "Implemented Firebase authentication, MFA, and JWT-based API access across the platform.",
      "Built Node.js, Express.js, GraphQL, and Strapi services for education workflows.",
      "Delivered teacher dashboard features, scheduled PDF reports, React interfaces, and Flutter companion app work.",
    ],
    stack: ["React.js", "Node.js", "Express.js", "GraphQL", "Strapi", "MongoDB", "Firebase", "Flutter"],
  },
  {
    slug: "speakup-now",
    tag: "Connected web app",
    title: "SpeakUp Now",
    href: "/about#speakup-now",
    role: "Full-stack developer",
    year: "2023",
    impact: "Improved interaction quality across authenticated, third-party connected product workflows.",
    summary: "A responsive web product focused on clean UX, secure authentication, and reliable connected workflows.",
    context: "The work centered on turning product requirements into usable interfaces while keeping access control and third-party integrations consistent.",
    contribution: [
      "Built responsive product interfaces with reusable component structure and consistent design patterns.",
      "Layered OAuth and JWT authentication into connected API workflows.",
      "Improved cross-device reliability through access-control checks and consistency testing.",
    ],
    stack: ["React.js", "Node.js", "REST APIs", "OAuth", "JWT", "Responsive UI"],
  },
  {
    slug: "retrospective",
    tag: "Agile collaboration",
    title: "Retrospective",
    href: "/about#retrospective",
    role: "Full-stack developer",
    year: "2022",
    impact: "Helped product and QA teams move ambiguous Agile workflow requirements into shipped features.",
    summary: "A collaboration product for Agile retrospectives, reusable team modules, and REST-connected workflow features.",
    context: "The product needed reusable UI modules and practical debugging support while feature requirements evolved with product and QA feedback.",
    contribution: [
      "Built reusable React components adopted across multiple team modules.",
      "Implemented REST-connected collaboration features for Agile workflow use cases.",
      "Supported system-level debugging and manual QA alongside feature delivery.",
    ],
    stack: ["React.js", "JavaScript", "REST APIs", "Agile", "Reusable UI", "Manual QA"],
  },
  {
    slug: "agentic-dynamic-ui",
    tag: "Open source",
    title: "Agentic Dynamic UI",
    href: "/about#agentic-dynamic-ui",
    role: "AI engineer",
    year: "2025",
    impact: "Moved AI interactions beyond chat with live, task-specific interfaces and human-approved writes.",
    summary: "An AI agent that responds with interactive React components instead of plain text, choosing the right interface for each task.",
    context: "Chat alone was too limiting for workflows that needed forms, tables, confirmation cards, and safe writes to connected systems.",
    contribution: [
      "Streamed AG-UI components with server-held state for responsive agent workflows.",
      "Generated task-specific forms, tables, and confirmation cards from live context.",
      "Added human-in-the-loop approval before writes reached connected systems.",
    ],
    stack: ["AG-UI", "Generative UI", "React", "TypeScript", "AI Agents", "Human-in-the-loop"],
  },
] as const;

export const experience = [
  { company: "Irisidea", role: "Software Engineer", meta: "Dec 2024 – Present · Bengaluru", note: "Shipping tracking and AI products across frontend, backend, integrations, real-time workflows, and reusable packages." },
  { company: "Yellow Owl", role: "SDE", meta: "May 2024 – Nov 2024 · Coimbatore", note: "Built education product workflows with React, TypeScript, Node.js, GraphQL, Strapi, authentication, and reporting." },
  { company: "Ethereal Covenant", role: "Full-stack Developer", meta: "Jan 2023 – Sep 2023 · Bengaluru", note: "Delivered responsive product interfaces, backend services, authentication, and connected workflows." },
  { company: "Dbaux Technologies", role: "Full-stack Developer", meta: "Nov 2021 – Nov 2022 · Bengaluru", note: "Built reusable React modules and REST-connected collaboration features in an Agile product team." },
] as const;

export const skillGroups = [
  { title: "Languages & runtime", items: ["TypeScript", "JavaScript", "Node.js", "SQL"] },
  { title: "Backend & APIs", items: ["Express.js", "GraphQL", "REST APIs", "OAuth", "JWT", "Server-Sent Events"] },
  { title: "Data & messaging", items: ["MySQL", "MongoDB", "Redis", "Firebase", "Prisma", "Streaming workflows"] },
  { title: "Cloud & AWS", items: ["AWS EC2", "AWS ECS", "AWS EKS", "Amazon S3", "AWS Lambda", "Docker"] },
  { title: "Integrations", items: ["Google Maps", "Microsoft Entra ID", "Microsoft Graph", "OneDrive", "Third-party APIs"] },
  { title: "Product & AI systems", items: ["React", "Next.js", "LLM features", "RAG", "Tool integrations", "Agent workflows"] },
] as const;
